CREATE TABLE kafka_monitoring (
  id                 BIGINT GENERATED BY DEFAULT AS identity,
  created_date       TIMESTAMP,
  last_modified_date TIMESTAMP,
  is_delete          BOOLEAN NOT NULL,
  kafka_offset       BIGINT,
  kafka_partition    INTEGER,
  kafka_topic        VARCHAR(255),
  PRIMARY KEY (id)
)